##
## Test Suites
##

    modified.files.includes[relevant][commerce-catalog-web-playwright-rule]=**
    relevant.rule.names=commerce-catalog-web-playwright-rule

    test.batch.names[relevant][commerce-catalog-web-playwright-rule]=\
        playwright-js-tomcat101-mysql57

    #
    # Relevant
    #

    playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][commerce-catalog-web-playwright-rule]=\
        commerce-catalog-web.main

##
## Testray
##

    testray.main.component.name=Commerce