copyLibs {
	enabled = true
}

dependencies {
	compileOnly group: "io.rest-assured", name: "rest-assured", version: "3.3.0"
	compileOnly group: "org.apache.httpcomponents", name: "httpclient", version: "4.5.3"
	compileOnly group: "org.codehaus.groovy", name: "groovy-xml", version: "2.4.15"
	compileOnly group: "org.codehaus.groovy", name: "groovy", version: "2.4.15"
	compileOnly group: "org.apache.httpcomponents", name: "httpcore", version: "4.4.6"
	compileOnly group: "org.hamcrest", name: "hamcrest-core", version: "1.3"
	compileOnly group: "org.hamcrest", name: "hamcrest-library", version: "1.3"
	compileOnly group: "org.codehaus.groovy", name: "groovy-json", version: "2.5.6"
	compileOnly group: "org.ccil.cowan.tagsoup", name: "tagsoup", version: "1.2.1"
	compileOnly group: "org.apache.commons", name: "commons-lang3", version: "3.4"
	compileOnly group: "uk.co.datumedge", name: "hamcrest-json", version: "0.2"
	compileOnly group: "org.skyscreamer", name: "jsonassert", version: "1.1.1"

	testIntegrationCompile group: "com.fasterxml.jackson.core", name: "jackson-core", version: "2.9.8"
	testIntegrationCompile group: "com.fasterxml.jackson.core", name: "jackson-databind", version: "2.9.8"

	testIntegrationCompile group: "com.jayway.jsonpath", name: "json-path", version: "2.2.0"
//	testIntegrationCompile group: "com.liferay.arquillian", name: "com.liferay.arquillian.arquillian-container-liferay", version: "1.0.7"
//	testIntegrationCompile group: "com.liferay.arquillian", name: "com.liferay.arquillian.arquillian-deployment-generator-bnd", version: "1.0.4"
	testIntegrationCompile group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	testIntegrationCompile group: "io.rest-assured", name: "rest-assured-common", version: "3.3.0"
//	testIntegrationCompile group: "org.jboss.arquillian.junit", name: "arquillian-junit-container", version: "1.1.10.Final"
	testIntegrationCompile project(":apps:headless:headless-document-library:headless-document-library-api")
	testIntegrationCompile project(":apps:portal-vulcan:portal-vulcan-api")
	testIntegrationCompile project(":test:arquillian-extension-junit-bridge")
}















//dependencies {
//	compileOnly group: "com.fasterxml.jackson.core", name: "jackson-databind", version: "2.9.8"
//	compileOnly group: "org.apache.cxf", name: "cxf-rt-frontend-jaxrs", version: "3.2.4"
//	compileOnly group: "org.assertj", name: "assertj-core", version: "3.10.0"
//	compileOnly project(":apps:headless-apio:portal:portal-apio-test-util")
//
//	testIntegrationCompile group: "com.jayway.jsonpath", name: "json-path", version: "2.2.0"
//	testIntegrationCompile group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
//	testIntegrationCompile group: "org.apache.httpcomponents", name: "httpasyncclient", version: "4.1.3"
//	testIntegrationCompile group: "org.apache.httpcomponents", name: "httpclient", version: "4.5.3"
//	testIntegrationCompile group: "org.apache.httpcomponents", name: "httpcore", version: "4.4.6"
//	testIntegrationCompile group: "org.apache.httpcomponents", name: "httpcore-nio", version: "4.4.6"
//	testIntegrationCompile project(":apps:apio-architect:apio-architect-api")
//	testIntegrationCompile project(":apps:headless-apio:folder:folder-apio-api")
//	testIntegrationCompile project(":apps:headless-apio:portal:portal-apio-api")
//	testIntegrationCompile project(":apps:petra:petra-json-web-service-client")
//	testIntegrationCompile project(":core:registry-api")
//	testIntegrationCompile project(":test:arquillian-extension-junit-bridge")
//}

/*
dependencies {
	testIntegrationCompile group: "com.fasterxml.jackson.core", name: "jackson-core", version: "2.9.8"
	testIntegrationCompile group: "com.fasterxml.jackson.core", name: "jackson-databind", version: "2.9.8"
	testIntegrationCompile group: "com.jayway.jsonpath", name: "json-path", version: "2.2.0"
	testIntegrationCompile group: "com.liferay.arquillian", name: "com.liferay.arquillian.arquillian-container-liferay", version: "1.0.7"
	testIntegrationCompile group: "com.liferay.arquillian", name: "com.liferay.arquillian.arquillian-deployment-generator-bnd", version: "1.0.4"
	testIntegrationCompile group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	testIntegrationCompile group: "io.rest-assured", name: "rest-assured", version: "3.3.0"
	testIntegrationCompile group: "io.rest-assured", name: "rest-assured-common", version: "3.3.0"
//	testIntegrationCompile group: "org.jboss.arquillian.junit", name: "arquillian-junit-container", version: "1.1.10.Final"
	testIntegrationCompile group: "uk.co.datumedge", name: "hamcrest-json", version: "0.2"
	testIntegrationCompile project(":apps:headless:headless-document-library:headless-document-library-api")
	testIntegrationCompile project(":apps:portal-vulcan:portal-vulcan-api")
//	testIntegrationCompile project(":test:arquillian-extension-junit-bridge")
}
*/