##
## Test Suites
##

    modified.files.includes[relevant][site-admin-web-playwright-rule]=**
    relevant.rule.names=site-admin-web-playwright-rule

    test.batch.names[relevant][site-admin-web-playwright-rule]=\
        playwright-js-tomcat101-mysql57

    #
    # Relevant
    #

    playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][site-admin-web-playwright-rule]=\
        site-admin-web.main

##
## Testray
##

    testray.main.component.name=Sites Administration