/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.kernel.upgrade.recorder;

import com.liferay.petra.string.StringPool;
import com.liferay.portal.kernel.dao.jdbc.util.CallableStatementWrapper;
import com.liferay.portal.kernel.dao.jdbc.util.ConnectionWrapper;
import com.liferay.portal.kernel.dao.jdbc.util.PreparedStatementWrapper;
import com.liferay.portal.kernel.dao.jdbc.util.StatementWrapper;
import com.liferay.portal.kernel.db.partition.DBPartition;
import com.liferay.portal.kernel.security.auth.CompanyThreadLocal;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CopyOnWriteArrayList;

/**
 * @author István András Dézsi
 */
public class UpgradeSQLRecorder {

	public static Connection getConnectionWrapper(Connection connection) {
		return getConnectionWrapper(connection, StringPool.BLANK);
	}

	public static Connection getConnectionWrapper(
		Connection connection, String upgradeProcessClassName) {

		_upgradeProcessClassName = upgradeProcessClassName;

		if (!_enabled) {
			return connection;
		}

		return new ConnectionWrapper(connection) {

			@Override
			public Statement createStatement() throws SQLException {
				return _wrap(super.createStatement());
			}

			@Override
			public Statement createStatement(
					int resultSetType, int resultSetConcurrency)
				throws SQLException {

				return _wrap(
					super.createStatement(resultSetType, resultSetConcurrency));
			}

			@Override
			public Statement createStatement(
					int resultSetType, int resultSetConcurrency,
					int resultSetHoldability)
				throws SQLException {

				return _wrap(
					super.createStatement(
						resultSetType, resultSetConcurrency,
						resultSetHoldability));
			}

			@Override
			public CallableStatement prepareCall(String sql)
				throws SQLException {

				return (CallableStatement)_wrap(super.prepareCall(sql));
			}

			@Override
			public CallableStatement prepareCall(
					String sql, int resultSetType, int resultSetConcurrency)
				throws SQLException {

				return (CallableStatement)_wrap(
					super.prepareCall(
						sql, resultSetType, resultSetConcurrency));
			}

			@Override
			public CallableStatement prepareCall(
					String sql, int resultSetType, int resultSetConcurrency,
					int resultSetHoldability)
				throws SQLException {

				return (CallableStatement)_wrap(
					super.prepareCall(
						sql, resultSetType, resultSetConcurrency,
						resultSetHoldability));
			}

			@Override
			public PreparedStatement prepareStatement(String sql)
				throws SQLException {

				return (PreparedStatement)_wrap(super.prepareStatement(sql));
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, int autoGeneratedKeys)
				throws SQLException {

				return (PreparedStatement)_wrap(
					super.prepareStatement(sql, autoGeneratedKeys));
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, int resultSetType, int resultSetConcurrency)
				throws SQLException {

				return (PreparedStatement)_wrap(
					super.prepareStatement(
						sql, resultSetType, resultSetConcurrency));
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, int resultSetType, int resultSetConcurrency,
					int resultSetHoldability)
				throws SQLException {

				return (PreparedStatement)_wrap(
					super.prepareStatement(
						sql, resultSetType, resultSetConcurrency,
						resultSetHoldability));
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, int[] columnIndexes)
				throws SQLException {

				return (PreparedStatement)_wrap(
					super.prepareStatement(sql, columnIndexes));
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, String[] columnNames)
				throws SQLException {

				return (PreparedStatement)_wrap(
					super.prepareStatement(sql, columnNames));
			}

		};
	}

	public static List<String> getFailedSQLs() {
		return _failedSQLs;
	}

	public static Map<String, Long> getSQLExecutionTimes() {
		return _sqlExecutionTimes;
	}

	public static void start() {
		_enabled = true;

		_failedSQLs.clear();

		_sqlExecutionTimes.clear();
	}

	public static void stop() {
		_enabled = false;
	}

	private static <T> T _execute(SQLCallable<T> sqlCallable, Object object)
		throws SQLException {

		long startTime = System.currentTimeMillis();

		try {
			return sqlCallable.call();
		}
		catch (SQLException sqlException) {
			String sql = _extractSQL(object);

			if (sql != null) {
				String message = sqlException.getMessage();

				if (Validator.isBlank(message)) {
					_failedSQLs.add("SQL: " + sql);
				}
				else {
					_failedSQLs.add(
						StringBundler.concat(
							"SQL: ", sql, ";\tError: ", message));
				}
			}

			throw sqlException;
		}
		finally {
			String sql = _extractSQL(object);

			if (sql != null) {
				sql += StringPool.SEMICOLON;

				long duration = System.currentTimeMillis() - startTime;

				if (Validator.isBlank(_upgradeProcessClassName)) {
					_sqlExecutionTimes.put(sql, duration);
				}
				else if (DBPartition.isPartitionEnabled()) {
					_sqlExecutionTimes.put(
						StringBundler.concat(
							_upgradeProcessClassName, StringPool.AT,
							String.valueOf(CompanyThreadLocal.getCompanyId()),
							StringPool.PIPE, sql),
						duration);
				}
				else {
					_sqlExecutionTimes.put(
						_upgradeProcessClassName + StringPool.PIPE + sql,
						duration);
				}
			}
		}
	}

	private static String _extractSQL(Object object) {
		if (object instanceof String) {
			return (String)object;
		}
		else if (object instanceof Statement) {
			String string = object.toString();

			int index = string.indexOf(':');

			if (index >= 0) {
				return StringUtil.trim(string.substring(index + 1));
			}
		}

		return null;
	}

	private static <T extends Statement> T _wrap(T statement) {
		if (statement instanceof CallableStatement) {
			return (T)new CallableStatementWrapper(
				(CallableStatement)statement) {

				@Override
				public boolean execute() throws SQLException {
					return _execute(() -> super.execute(), statement);
				}

				@Override
				public int[] executeBatch() throws SQLException {
					return _execute(() -> super.executeBatch(), statement);
				}

				@Override
				public ResultSet executeQuery() throws SQLException {
					return _execute(() -> super.executeQuery(), statement);
				}

				@Override
				public int executeUpdate() throws SQLException {
					return _execute(() -> super.executeUpdate(), statement);
				}

			};
		}
		else if (statement instanceof PreparedStatement) {
			return (T)new PreparedStatementWrapper(
				(PreparedStatement)statement) {

				@Override
				public boolean execute() throws SQLException {
					return _execute(() -> super.execute(), statement);
				}

				@Override
				public int[] executeBatch() throws SQLException {
					return _execute(() -> super.executeBatch(), statement);
				}

				@Override
				public ResultSet executeQuery() throws SQLException {
					return _execute(() -> super.executeQuery(), statement);
				}

				@Override
				public int executeUpdate() throws SQLException {
					return _execute(() -> super.executeUpdate(), statement);
				}

			};
		}

		return (T)new StatementWrapper(statement) {

			@Override
			public boolean execute(String sql) throws SQLException {
				return _execute(() -> super.execute(sql), sql);
			}

			@Override
			public int[] executeBatch() throws SQLException {
				return _execute(() -> super.executeBatch(), statement);
			}

			@Override
			public ResultSet executeQuery(String sql) throws SQLException {
				return _execute(() -> super.executeQuery(sql), sql);
			}

			@Override
			public int executeUpdate(String sql) throws SQLException {
				return _execute(() -> super.executeUpdate(sql), sql);
			}

			@Override
			public boolean execute(String sql, int autoGeneratedKeys)
				throws SQLException {

				return _execute(
					() -> super.execute(sql, autoGeneratedKeys), sql);
			}

			@Override
			public boolean execute(String sql, int[] columnIndexes)
				throws SQLException {

				return _execute(() -> super.execute(sql, columnIndexes), sql);
			}

			@Override
			public boolean execute(String sql, String[] columnNames)
				throws SQLException {

				return _execute(() -> super.execute(sql, columnNames), sql);
			}

			@Override
			public int executeUpdate(String sql, int autoGeneratedKeys)
				throws SQLException {

				return _execute(
					() -> super.executeUpdate(sql, autoGeneratedKeys), sql);
			}

			@Override
			public int executeUpdate(String sql, int[] columnIndexes)
				throws SQLException {

				return _execute(
					() -> super.executeUpdate(sql, columnIndexes), sql);
			}

			@Override
			public int executeUpdate(String sql, String[] columnNames)
				throws SQLException {

				return _execute(
					() -> super.executeUpdate(sql, columnNames), sql);
			}

		};
	}

	private static boolean _enabled;
	private static final List<String> _failedSQLs =
		new CopyOnWriteArrayList<>();
	private static final Map<String, Long> _sqlExecutionTimes =
		new ConcurrentHashMap<>();
	private static volatile String _upgradeProcessClassName = StringPool.BLANK;

	@FunctionalInterface
	private interface SQLCallable<R> {

		public R call() throws SQLException;

	}

}