#
# This is a generated file.
#

api.version=v1.0
entity.class.name=com.liferay.headless.sites.dto.v1_0.Site
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Headless.Sites)
osgi.jaxrs.resource=true