/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.chess.model.impl;

import com.liferay.chess.model.ChessGame;
import com.liferay.chess.model.ChessGameModel;
import com.liferay.chess.model.ChessGameSoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ChessGame service. Represents a row in the &quot;ChessGame&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ChessGameModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChessGameImpl}.
 * </p>
 *
 * @author Rubén Pulido
 * @see ChessGameImpl
 * @generated
 */
@JSON(strict = true)
public class ChessGameModelImpl
	extends BaseModelImpl<ChessGame> implements ChessGameModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a chess game model instance should use the <code>ChessGame</code> interface instead.
	 */
	public static final String TABLE_NAME = "ChessGame";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"chessGameId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"whitePlayerId", Types.BIGINT},
		{"blackPlayerId", Types.BIGINT}, {"moves", Types.VARCHAR},
		{"winnerPlayerId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("chessGameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("whitePlayerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("blackPlayerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("moves", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("winnerPlayerId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ChessGame (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,chessGameId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,whitePlayerId LONG,blackPlayerId LONG,moves VARCHAR(75) null,winnerPlayerId LONG)";

	public static final String TABLE_SQL_DROP = "drop table ChessGame";

	public static final String ORDER_BY_JPQL =
		" ORDER BY chessGame.modifiedDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ChessGame.modifiedDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long MODIFIEDDATE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ChessGame toModel(ChessGameSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ChessGame model = new ChessGameImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setUuid(soapModel.getUuid());
		model.setChessGameId(soapModel.getChessGameId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setWhitePlayerId(soapModel.getWhitePlayerId());
		model.setBlackPlayerId(soapModel.getBlackPlayerId());
		model.setMoves(soapModel.getMoves());
		model.setWinnerPlayerId(soapModel.getWinnerPlayerId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ChessGame> toModels(ChessGameSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ChessGame> models = new ArrayList<ChessGame>(soapModels.length);

		for (ChessGameSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ChessGameModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _chessGameId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setChessGameId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _chessGameId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ChessGame.class;
	}

	@Override
	public String getModelClassName() {
		return ChessGame.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ChessGame, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ChessGame, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ChessGame, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((ChessGame)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ChessGame, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ChessGame, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ChessGame)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ChessGame, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ChessGame, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ChessGame>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ChessGame.class.getClassLoader(), ChessGame.class,
			ModelWrapper.class);

		try {
			Constructor<ChessGame> constructor =
				(Constructor<ChessGame>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ChessGame, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ChessGame, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ChessGame, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ChessGame, Object>>();
		Map<String, BiConsumer<ChessGame, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ChessGame, ?>>();

		attributeGetterFunctions.put("mvccVersion", ChessGame::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<ChessGame, Long>)ChessGame::setMvccVersion);
		attributeGetterFunctions.put("uuid", ChessGame::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<ChessGame, String>)ChessGame::setUuid);
		attributeGetterFunctions.put("chessGameId", ChessGame::getChessGameId);
		attributeSetterBiConsumers.put(
			"chessGameId",
			(BiConsumer<ChessGame, Long>)ChessGame::setChessGameId);
		attributeGetterFunctions.put("groupId", ChessGame::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<ChessGame, Long>)ChessGame::setGroupId);
		attributeGetterFunctions.put("companyId", ChessGame::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<ChessGame, Long>)ChessGame::setCompanyId);
		attributeGetterFunctions.put("userId", ChessGame::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<ChessGame, Long>)ChessGame::setUserId);
		attributeGetterFunctions.put("userName", ChessGame::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<ChessGame, String>)ChessGame::setUserName);
		attributeGetterFunctions.put("createDate", ChessGame::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ChessGame, Date>)ChessGame::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", ChessGame::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ChessGame, Date>)ChessGame::setModifiedDate);
		attributeGetterFunctions.put(
			"whitePlayerId", ChessGame::getWhitePlayerId);
		attributeSetterBiConsumers.put(
			"whitePlayerId",
			(BiConsumer<ChessGame, Long>)ChessGame::setWhitePlayerId);
		attributeGetterFunctions.put(
			"blackPlayerId", ChessGame::getBlackPlayerId);
		attributeSetterBiConsumers.put(
			"blackPlayerId",
			(BiConsumer<ChessGame, Long>)ChessGame::setBlackPlayerId);
		attributeGetterFunctions.put("moves", ChessGame::getMoves);
		attributeSetterBiConsumers.put(
			"moves", (BiConsumer<ChessGame, String>)ChessGame::setMoves);
		attributeGetterFunctions.put(
			"winnerPlayerId", ChessGame::getWinnerPlayerId);
		attributeSetterBiConsumers.put(
			"winnerPlayerId",
			(BiConsumer<ChessGame, Long>)ChessGame::setWinnerPlayerId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getChessGameId() {
		return _chessGameId;
	}

	@Override
	public void setChessGameId(long chessGameId) {
		_chessGameId = chessGameId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_columnBitmask = -1L;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getWhitePlayerId() {
		return _whitePlayerId;
	}

	@Override
	public void setWhitePlayerId(long whitePlayerId) {
		_whitePlayerId = whitePlayerId;
	}

	@JSON
	@Override
	public long getBlackPlayerId() {
		return _blackPlayerId;
	}

	@Override
	public void setBlackPlayerId(long blackPlayerId) {
		_blackPlayerId = blackPlayerId;
	}

	@JSON
	@Override
	public String getMoves() {
		if (_moves == null) {
			return "";
		}
		else {
			return _moves;
		}
	}

	@Override
	public void setMoves(String moves) {
		_moves = moves;
	}

	@JSON
	@Override
	public long getWinnerPlayerId() {
		return _winnerPlayerId;
	}

	@Override
	public void setWinnerPlayerId(long winnerPlayerId) {
		_winnerPlayerId = winnerPlayerId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ChessGame.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ChessGame.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ChessGame toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ChessGame>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ChessGameImpl chessGameImpl = new ChessGameImpl();

		chessGameImpl.setMvccVersion(getMvccVersion());
		chessGameImpl.setUuid(getUuid());
		chessGameImpl.setChessGameId(getChessGameId());
		chessGameImpl.setGroupId(getGroupId());
		chessGameImpl.setCompanyId(getCompanyId());
		chessGameImpl.setUserId(getUserId());
		chessGameImpl.setUserName(getUserName());
		chessGameImpl.setCreateDate(getCreateDate());
		chessGameImpl.setModifiedDate(getModifiedDate());
		chessGameImpl.setWhitePlayerId(getWhitePlayerId());
		chessGameImpl.setBlackPlayerId(getBlackPlayerId());
		chessGameImpl.setMoves(getMoves());
		chessGameImpl.setWinnerPlayerId(getWinnerPlayerId());

		chessGameImpl.resetOriginalValues();

		return chessGameImpl;
	}

	@Override
	public int compareTo(ChessGame chessGame) {
		int value = 0;

		value = DateUtil.compareTo(
			getModifiedDate(), chessGame.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ChessGame)) {
			return false;
		}

		ChessGame chessGame = (ChessGame)object;

		long primaryKey = chessGame.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		ChessGameModelImpl chessGameModelImpl = this;

		chessGameModelImpl._originalUuid = chessGameModelImpl._uuid;

		chessGameModelImpl._originalGroupId = chessGameModelImpl._groupId;

		chessGameModelImpl._setOriginalGroupId = false;

		chessGameModelImpl._originalCompanyId = chessGameModelImpl._companyId;

		chessGameModelImpl._setOriginalCompanyId = false;

		chessGameModelImpl._setModifiedDate = false;

		chessGameModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ChessGame> toCacheModel() {
		ChessGameCacheModel chessGameCacheModel = new ChessGameCacheModel();

		chessGameCacheModel.mvccVersion = getMvccVersion();

		chessGameCacheModel.uuid = getUuid();

		String uuid = chessGameCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			chessGameCacheModel.uuid = null;
		}

		chessGameCacheModel.chessGameId = getChessGameId();

		chessGameCacheModel.groupId = getGroupId();

		chessGameCacheModel.companyId = getCompanyId();

		chessGameCacheModel.userId = getUserId();

		chessGameCacheModel.userName = getUserName();

		String userName = chessGameCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			chessGameCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			chessGameCacheModel.createDate = createDate.getTime();
		}
		else {
			chessGameCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			chessGameCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			chessGameCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		chessGameCacheModel.whitePlayerId = getWhitePlayerId();

		chessGameCacheModel.blackPlayerId = getBlackPlayerId();

		chessGameCacheModel.moves = getMoves();

		String moves = chessGameCacheModel.moves;

		if ((moves != null) && (moves.length() == 0)) {
			chessGameCacheModel.moves = null;
		}

		chessGameCacheModel.winnerPlayerId = getWinnerPlayerId();

		return chessGameCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ChessGame, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ChessGame, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ChessGame, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ChessGame)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ChessGame, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ChessGame, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ChessGame, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ChessGame)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ChessGame>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _mvccVersion;
	private String _uuid;
	private String _originalUuid;
	private long _chessGameId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _whitePlayerId;
	private long _blackPlayerId;
	private String _moves;
	private long _winnerPlayerId;
	private long _columnBitmask;
	private ChessGame _escapedModel;

}