/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.chess.service.base;

import com.liferay.chess.model.ChessGame;
import com.liferay.chess.service.ChessGameLocalService;
import com.liferay.chess.service.persistence.ChessGamePersistence;
import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the chess game local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.chess.service.impl.ChessGameLocalServiceImpl}.
 * </p>
 *
 * @author Rubén Pulido
 * @see com.liferay.chess.service.impl.ChessGameLocalServiceImpl
 * @generated
 */
public abstract class ChessGameLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, ChessGameLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ChessGameLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.chess.service.ChessGameLocalServiceUtil</code>.
	 */

	/**
	 * Adds the chess game to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ChessGameLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param chessGame the chess game
	 * @return the chess game that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ChessGame addChessGame(ChessGame chessGame) {
		chessGame.setNew(true);

		return chessGamePersistence.update(chessGame);
	}

	/**
	 * Creates a new chess game with the primary key. Does not add the chess game to the database.
	 *
	 * @param chessGameId the primary key for the new chess game
	 * @return the new chess game
	 */
	@Override
	@Transactional(enabled = false)
	public ChessGame createChessGame(long chessGameId) {
		return chessGamePersistence.create(chessGameId);
	}

	/**
	 * Deletes the chess game with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ChessGameLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param chessGameId the primary key of the chess game
	 * @return the chess game that was removed
	 * @throws PortalException if a chess game with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ChessGame deleteChessGame(long chessGameId) throws PortalException {
		return chessGamePersistence.remove(chessGameId);
	}

	/**
	 * Deletes the chess game from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ChessGameLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param chessGame the chess game
	 * @return the chess game that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ChessGame deleteChessGame(ChessGame chessGame) {
		return chessGamePersistence.remove(chessGame);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return chessGamePersistence.dslQuery(dslQuery);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ChessGame.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return chessGamePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.chess.model.impl.ChessGameModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return chessGamePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.chess.model.impl.ChessGameModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return chessGamePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return chessGamePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return chessGamePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ChessGame fetchChessGame(long chessGameId) {
		return chessGamePersistence.fetchByPrimaryKey(chessGameId);
	}

	/**
	 * Returns the chess game matching the UUID and group.
	 *
	 * @param uuid the chess game's UUID
	 * @param groupId the primary key of the group
	 * @return the matching chess game, or <code>null</code> if a matching chess game could not be found
	 */
	@Override
	public ChessGame fetchChessGameByUuidAndGroupId(String uuid, long groupId) {
		return chessGamePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the chess game with the primary key.
	 *
	 * @param chessGameId the primary key of the chess game
	 * @return the chess game
	 * @throws PortalException if a chess game with the primary key could not be found
	 */
	@Override
	public ChessGame getChessGame(long chessGameId) throws PortalException {
		return chessGamePersistence.findByPrimaryKey(chessGameId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(chessGameLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ChessGame.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("chessGameId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			chessGameLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ChessGame.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"chessGameId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(chessGameLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ChessGame.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("chessGameId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<ChessGame>() {

				@Override
				public void performAction(ChessGame chessGame)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, chessGame);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(ChessGame.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return chessGamePersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return chessGameLocalService.deleteChessGame((ChessGame)persistedModel);
	}

	public BasePersistence<ChessGame> getBasePersistence() {
		return chessGamePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return chessGamePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the chess games matching the UUID and company.
	 *
	 * @param uuid the UUID of the chess games
	 * @param companyId the primary key of the company
	 * @return the matching chess games, or an empty list if no matches were found
	 */
	@Override
	public List<ChessGame> getChessGamesByUuidAndCompanyId(
		String uuid, long companyId) {

		return chessGamePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of chess games matching the UUID and company.
	 *
	 * @param uuid the UUID of the chess games
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of chess games
	 * @param end the upper bound of the range of chess games (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching chess games, or an empty list if no matches were found
	 */
	@Override
	public List<ChessGame> getChessGamesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<ChessGame> orderByComparator) {

		return chessGamePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the chess game matching the UUID and group.
	 *
	 * @param uuid the chess game's UUID
	 * @param groupId the primary key of the group
	 * @return the matching chess game
	 * @throws PortalException if a matching chess game could not be found
	 */
	@Override
	public ChessGame getChessGameByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {

		return chessGamePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the chess games.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.chess.model.impl.ChessGameModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of chess games
	 * @param end the upper bound of the range of chess games (not inclusive)
	 * @return the range of chess games
	 */
	@Override
	public List<ChessGame> getChessGames(int start, int end) {
		return chessGamePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of chess games.
	 *
	 * @return the number of chess games
	 */
	@Override
	public int getChessGamesCount() {
		return chessGamePersistence.countAll();
	}

	/**
	 * Updates the chess game in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ChessGameLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param chessGame the chess game
	 * @return the chess game that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ChessGame updateChessGame(ChessGame chessGame) {
		return chessGamePersistence.update(chessGame);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ChessGameLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		chessGameLocalService = (ChessGameLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ChessGameLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ChessGame.class;
	}

	protected String getModelClassName() {
		return ChessGame.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = chessGamePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected ChessGameLocalService chessGameLocalService;

	@Reference
	protected ChessGamePersistence chessGamePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}