/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.chess.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ChessGame service. Represents a row in the &quot;ChessGame&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.chess.model.impl.ChessGameModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.chess.model.impl.ChessGameImpl</code>.
 * </p>
 *
 * @author Rubén Pulido
 * @see ChessGame
 * @generated
 */
@ProviderType
public interface ChessGameModel
	extends BaseModel<ChessGame>, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a chess game model instance should use the {@link ChessGame} interface instead.
	 */

	/**
	 * Returns the primary key of this chess game.
	 *
	 * @return the primary key of this chess game
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this chess game.
	 *
	 * @param primaryKey the primary key of this chess game
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this chess game.
	 *
	 * @return the mvcc version of this chess game
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this chess game.
	 *
	 * @param mvccVersion the mvcc version of this chess game
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this chess game.
	 *
	 * @return the uuid of this chess game
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this chess game.
	 *
	 * @param uuid the uuid of this chess game
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the chess game ID of this chess game.
	 *
	 * @return the chess game ID of this chess game
	 */
	public long getChessGameId();

	/**
	 * Sets the chess game ID of this chess game.
	 *
	 * @param chessGameId the chess game ID of this chess game
	 */
	public void setChessGameId(long chessGameId);

	/**
	 * Returns the group ID of this chess game.
	 *
	 * @return the group ID of this chess game
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this chess game.
	 *
	 * @param groupId the group ID of this chess game
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this chess game.
	 *
	 * @return the company ID of this chess game
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this chess game.
	 *
	 * @param companyId the company ID of this chess game
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this chess game.
	 *
	 * @return the user ID of this chess game
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this chess game.
	 *
	 * @param userId the user ID of this chess game
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this chess game.
	 *
	 * @return the user uuid of this chess game
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this chess game.
	 *
	 * @param userUuid the user uuid of this chess game
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this chess game.
	 *
	 * @return the user name of this chess game
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this chess game.
	 *
	 * @param userName the user name of this chess game
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this chess game.
	 *
	 * @return the create date of this chess game
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this chess game.
	 *
	 * @param createDate the create date of this chess game
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this chess game.
	 *
	 * @return the modified date of this chess game
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this chess game.
	 *
	 * @param modifiedDate the modified date of this chess game
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the white player ID of this chess game.
	 *
	 * @return the white player ID of this chess game
	 */
	public long getWhitePlayerId();

	/**
	 * Sets the white player ID of this chess game.
	 *
	 * @param whitePlayerId the white player ID of this chess game
	 */
	public void setWhitePlayerId(long whitePlayerId);

	/**
	 * Returns the black player ID of this chess game.
	 *
	 * @return the black player ID of this chess game
	 */
	public long getBlackPlayerId();

	/**
	 * Sets the black player ID of this chess game.
	 *
	 * @param blackPlayerId the black player ID of this chess game
	 */
	public void setBlackPlayerId(long blackPlayerId);

	/**
	 * Returns the moves of this chess game.
	 *
	 * @return the moves of this chess game
	 */
	@AutoEscape
	public String getMoves();

	/**
	 * Sets the moves of this chess game.
	 *
	 * @param moves the moves of this chess game
	 */
	public void setMoves(String moves);

	/**
	 * Returns the winner player ID of this chess game.
	 *
	 * @return the winner player ID of this chess game
	 */
	public long getWinnerPlayerId();

	/**
	 * Sets the winner player ID of this chess game.
	 *
	 * @param winnerPlayerId the winner player ID of this chess game
	 */
	public void setWinnerPlayerId(long winnerPlayerId);

}