#
# Application
#

liferay.ai.hub.crawler.elasticsearch.host=
liferay.ai.hub.crawler.elasticsearch.pipeline=
liferay.ai.hub.crawler.elasticsearch.port=
liferay.ai.hub.crawler.max.crawl.depth=1
liferay.ai.hub.crawler.max.duration=30
liferay.ai.hub.crawler.url.queue.size.limit=50000

#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay.oauth.application.external.reference.codes=liferay-aihub-etc-spring-boot-oaua
liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081