domains:
    -   crawl_rules:
            -   pattern: "[?&]sort="
                policy: deny
                type: regex
            -   pattern: "[?&]order(by)?="
                policy: deny
                type: regex
            -   pattern: "[?&](filter|facet|tag)="
                policy: deny
                type: regex
            -   pattern: /calendar/
                policy: deny
                type: begins
        seed_urls:
            -   [$CRAWLER_SEED_URL$]
        url: [$CRAWLER_DOMAIN_URL$]
elasticsearch:
    host: [$CRAWLER_ELASTICSEARCH_HOST$]
    pipeline: [$CRAWLER_ELASTICSEARCH_PIPELINE$]
    pipeline_enabled: true
    port: [$CRAWLER_ELASTICSEARCH_PORT$]
max_crawl_depth: [$CRAWLER_MAX_CRAWL_DEPTH$]
max_duration: [$CRAWLER_MAX_DURATION$]
output_index: [$CRAWLER_OUTPUT_INDEX$]
output_sink: elasticsearch
url_queue_size_limit: [$CRAWLER_URL_QUEUE_SIZE_LIMIT$]